version: 1.13.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVER: 14.0
      ARCH: x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVER: 9.0
      ARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
- cmd: 7z x ninja.zip -oC:\projects\deps\ninja > nul
- cmd: set PATH=C:\projects\deps\ninja;%PATH%
- cmd: ninja --version
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%
- mkdir build
- cd build
- cmd: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release %CMakeArgs% ..
- sh: cmake -DCMAKE_BUILD_TYPE=Release ${CMakeArgs} ..
- cmake --build . --config Release --target install
- cpack
artifacts:
- path: 'build/*.7z'
- path: 'build/*.deb'
- path: 'build/*.tar.*'
