version: 1.13.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  DODEPLOY: false
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVER: 14.0
      ARCH: x64
      LSLBOOST: lslboost
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVER: 9.0
      ARCH: x86
      LSLBOOST: external
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      LSLBOOST: lslboost
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
- cmd: 7z x ninja.zip -oC:\projects\deps\ninja > nul
- cmd: set PATH=C:\projects\deps\ninja;%PATH%
- cmd: ninja --version
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%
- mkdir build
- cd build
- cmd: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLSL_LSLBOOST_PATH=%LSLBOOST% %CMakeArgs% ..
- sh: cmake -DCMAKE_BUILD_TYPE=Release -DLSL_LSLBOOST_PATH=${LSLBOOST} ${CMakeArgs} ..
- cmake --build . --config Release --target install
- cpack
artifacts:
- path: 'build/*.7z'
- path: 'build/*.deb'
- path: 'build/*.tar.*'
deploy:
- provider: BinTray
  username: tstenner
  api_key:
    secure: Fo9tIQnGjVnCXB3euItvYrt85A5O9FPqq7LEpsdOuwW+eOg1rwA5Q1HLp4yWDXAl
  subject: labstreaminglayer
  version: 1.13
  repo: LSL
  package: $(APPVEYOR_PROJECT_NAME)
  publish: true
  override: true
  on:
    DODEPLOY: true
